// <auto-generated />
namespace NBUY_MOD.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class firstMi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstMi));
        
        string IMigrationMetadata.Id
        {
            get { return "201912121726497_firstMi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
